### ISSUE TITLE
Podcast Chat

### ISSUE THREAD

**Issue by jamash** [mdo/feedback#112]
Hi Mark,

To quickly introduce myself I work for CDNify, we make the inter-webs fast.

I wanted to know if you'd like to join me for a quick chat on our podcast series? Be interesting to talk about the backstory of GitHub, your upcoming talk at the jQuery conference, and any projects you're currently working on.

Here's some of the past eps we've done: https://soundcloud.com/cdnify

Let me know what you think :)

Thanks,
Jamie

**Comment by mdo** [comment]
I'm flattered, but I think I'll pass for now. I've got a few things on my plate to finish up and sometimes I just hate talking about work :). Maybe sometime in the future?

<3
