### ISSUE TITLE
Podcast for newbs / beginners

### ISSUE THREAD

**Issue by vis-kid** [mdo/feedback#119]
Hi Mark,

I was wondering if you'd be interested being one of the first guests on a new podcast I'm working on? It’s called “Between | Screens” and the idea is to produce a couple of 15 minute audio knowledge bombs from each interview. Each episode will focus on one topic and goes into more technical detail but should stay beginner-friendly as well.

People I’ve interviewed so far include Avdi Grimm, Steve Klabnik, Brandon Mathis, Natalie Weizenbaum, Ryan Singer, Coby Chapple, designers from Facebook & edenspiekermann_ and a few other inspiring people whose work came across my way. Please take a look at the podcast http://betweenscreens.fm/ or my blog http://betweenpipes.com/.

Thanks and have a nice day,

-ed wassermnann

**Comment by mdo** [comment]
Sorry I missed this! I'm honored, but maybe another time? <3

**Comment by vis-kid** [comment]
Sure you're busy, I get it :)

Should I just contact you again in a couple of months or how should we proceed? 

Have a nice day,

-e
