### ISSUE TITLE
Open Source Project Advice

### ISSUE THREAD

**Issue by astephen2** [mdo/feedback#121]
Huge fan! You've had a lot of open source projects that seem to be both popular and well maintained. Any advice on how to market and manage an open source project?

**Comment by mdo** [comment]
I mostly just open source things that I think would be fun to create. Jekyll themes, CSS techniques, and front-end experiments are all things I find interesting to create and share with people. My goal is to keep that interest and get folks to ask questions, use code I write, or volunteer better ideas.

Before you put that stuff out there though, you need to make sure it's at least somewhat documented. A readme that states your goals, contents, how to contribute, etc is pretty essential. Keeping the project and docs focused is important, too.

Beyond that, open source things you find useful to yourself and others. Or even just fun things you wanted to try. Nothing wrong with open sourcing experiments that will probably not go anywhere—just consider it practice :).
