### ISSUE TITLE
Thanks from Wire!

### ISSUE THREAD

**Issue by teller** [mdo/feedback#122]
Hi Mark,

Just wanted to say Thanks! for featuring Wire on Bootstrap Expo. Sent us some much appreciated traffic and new users :)

What's the best address to send couple of our tshirts in return?

Cheers
Siim

**Comment by mdo** [comment]
Aww, shucks, didn't see this for some reason. No sweat though, using Bootstrap is enough ;).

**Comment by teller** [comment]
The offer still stands :) I'm siim@wire.com on Wire.
