### ISSUE TITLE
How do you deal with vertical spacing in Bootstrap?

### ISSUE THREAD

**Issue by s10wen** [mdo/feedback#123]
For example:
https://vine.co/v/bgVKPtrzi61

**Comment by mdo** [comment]
Right now we have no utilities for vertical spacing. We're looking into adding that in v4—including some more generic placement, alignment, and spacing classes—but I've no idea right now what would be useful for the masses here.

A number of folks have asked for this in the past, but given the varied layouts one could use, I don't know off the top of my head if there's a single approach we could use for that.

You have any thoughts on what might work?

**Comment by s10wen** [comment]
@mdo thanks for the reply, here's my thoughts:

Recently I've found rather than tackling whole site layouts in one go, I'll create a stylesheet page first.

On the stylesheet page I have every bootstrap element laid out, with a header / footer, then I create custom modules upon this. I work on small chunks that are reusable, I find this helps so I'm not resolving the same problems over and over.

With each module when I come to a vertical spacing issue. I have a global vertical height set `$vertical-height: 12px;`. Then I use multiples of that value e.g. `margin-bottom: $vertical-height * 2` and fit the design around what works.

I've tried other ideas for automated fixes, but then trying to keep things browser compatible and JavaScript minimal becomes tricky.

So, at the minute, although I style each module individually which takes a bit more time than an automated global fix would I'm confident that it works.

As you said though with varied layouts it becomes difficult to find a 'one solution fits all' scenario. Personally I tend to work / design in the browser and change styles to fit with existing solutions. However, this isn't always possible if you're required to follow a complex design that can't be changed, but that's another conversation :wink:

**Comment by mwsasser** [comment]
Nice to know you are looking into this for bootstrap 4.  It is pretty vexing.

**Comment by mdo** [comment]
Not trying to discourage conversation, but I'll close this out. I'll be looking into it, but I've still little to no idea what form this kind of stuff is best served as. Might leave it vague and ask for suggestions once we do the alpha release.
