### ISSUE TITLE
Pimer open source? What's the chance?

### ISSUE THREAD

**Issue by Misiu** [mdo/feedback#124]
Hi there, I recently found Your post about GitHib's CSS. I want to create ticket (issues) system that will look and feel like GitHub.
I don't want to rip CSS from GitHub so I started searching for style guides and I found Your blog where You mention that GitHub is using Primer and that sadly it isn't open source.
Post was from July 23, 2014 so maybe something changed from that time.
Probably I'm not first person which would like to create interface like GitHub.
I hope that Primer will be open or maybe already is :smile: 
Please let us know.

**Comment by mdo** [comment]
I really want to release it, and the status on that effort is :soon:.

**Comment by Misiu** [comment]
@mdo those are awesome news :+1: 
I was planning to use bootstrap, but for now I'll finish server-side code and wait for primer.
Are You planning to add(release) JavaScript components, like for example select menu (https://github.com/styleguide/css/13.0)?

**Comment by Misiu** [comment]
I just noticed Primer is released, definitively must give it a try!
