### ISSUE TITLE
Invitation for JSConfUY 2015 - 13th and 14th March

### ISSUE THREAD

**Issue by pricco** [mdo/feedback#125]
Hey Mark,

As part of the JSConfUY / CSSConfUY, the JavaScript and CSS conference in Uruguay, We'd like to invite you to be one of our speakers in the 2015 edition. It would be great to hear bootstrap from first hand.

The conference will be on March 13th and 14th of 2015 here at Montevideo.
You can look at some [videos](https://www.youtube.com/user/jsconfuy) of the [previous event](http://2014.jsconf.uy/).
We'll cover your flights and accommodation.

It would be awesome to have you here.

Regards,
Pablo Ricco

**Comment by mdo** [comment]
Hey there! Sorry, but I'll be in Oxford for another conference at that time. Thanks for considering me though!

**Comment by pricco** [comment]
Hey Mark,

We're moving the conference to April 24th and 25th due to some venue restrictions.
If you think you will be available at that time we would love having you here!

Regards,
Pablo Ricco
