### ISSUE TITLE
Tossing an idea around in my head about loading pages... thoughts?

### ISSUE THREAD

**Issue by Annonomus-Penguin** [mdo/feedback#126]
I haven't been the first to try to change the way websites are loaded (cough, cough, ***local storage***), and maybe I'm too inexperienced to make this efficient here but I see a huge inefficiency in modern websites. I know you have a lot of experience in web development and I thought you'd be a good person to pitch this idea to.

**Loading.**

Current methods seem somewhat inefficient. They're practical and simple, but not the sort of thing that would be ideal when even milliseconds count. There seems to be a few major issues with this method's speed:

 1. A lot of elements are re-loaded that don't need to. Caching and asynchronous loading techniques have grown in the past few years. However, things like your navbar and the general layout of the page don't change on each request. It'd be a lot more efficient in my opinion to have the JS code fetch the content async and then parse a JSON request and then render the contents. For example, it might fetch from the server a list of all of the items in a thread for a page like this. It'd requires a lot less data because the main HTML page could be cached.
 2. Pages with a ton of resources have an issue where it has to "ping" the server with little data to see if anything has changed. I guess a browser could "look ahead" at the resources it'll need in the future and load those elements before they're needed, but do browsers do that?

It would seem ideal to use the JSON idea in the first bullet point, but I'm not sure how well it would work.

Thoughts? Do any companies use this? Any frameworks developed for this? I notice eBay's body loads a bit after the header, so I'm wondering if they do that.

**On a side note...** while speaking of the local storage caching technique, what are your opinions?

**Comment by mdo** [comment]
Sorry, but that's not really my speciality :grin:.

You might want to check out something like https://github.com/defunkt/jquery-pjax though. We use that here at GitHub to quickly load sections of pages content of reloading the entire page. Not sure what else there is though for this. Hope that helps some!

**Comment by Annonomus-Penguin** [comment]
@mdo what you showed me was very similar to what I was saying, although my idea would be much less portable (although faster? on huge sites). Might try that out (thanks!)

Will have to benchmark this to see if I can get something to work that's more efficient than pjax and then blog about it [on my blog that hasn't been created yet due to Bootstrap v4 not out yet :smirk:.
