### ISSUE TITLE
Less or Sass

### ISSUE THREAD

**Issue by hahmed** [mdo/feedback#127]
Which css framework do you recommend learning? Less or Sass, what have you found to better suit your workflow?

What do you use at Github?

Thanks

**Comment by mdo** [comment]
Either is fine honestly. They have near complete parity on features. I use Less with Bootstrap and Sass at GitHub, but most times they feel rather interchangeable. Sass has cleaner syntax IMO and a larger community behind it('s development).

These days I would lean towards Sass though if I had to pick.
