### ISSUE TITLE
Laptop Stickers or No Laptop Stickers?

### ISSUE THREAD

**Issue by tarebyte** [mdo/feedback#130]
There seems to be two major camps, those that have their entire laptop covered in stickers, and those that refuse to have any stickers on their laptops at all.

I have found that a lot of designers don't like having laptop stickers, so I was just curious where you fell in that spectrum.

Btw, I really enjoy [your blog](http://markdotto.com/), and the documentation for [Bootstrap](http://getbootstrap.com/) is pretty kick ass.

Thanks @mdo!

**Comment by mdo** [comment]
No stickers for me on my laptop—I like the smooth aluminum :).
