### ISSUE TITLE
Why is Open Source so important?

### ISSUE THREAD

**Issue by michaelaris** [mdo/feedback#131]
Hey Mark, 

I'm currently a student at the University of Waterloo and I've co-written an article about you and @fat creating Bootstrap and Open Source. We're trying to convince big business that sometimes it's better to let the curtain drop and expose their internal operations in order to build a better product. You can check out our post here: http://smbp.uwaterloo.ca/2015/02/built-together-built-better-with-github/

I'd love to pick your brain if you have a minute to talk about open source. Feel free to reach out to me here and maybe we can schedule something. Cheers!

**Comment by mdo** [comment]
Thanks for the mention and reaching out <3. If you have specific questions about open source or Bootstrap, just fire away. I'm always open to answering questions here. And to, briefly, answer your title question: OS is important on many levels—accessibility of information, sharing of knowledge, iteration on existing technologies, etc. All those, and more, come together to make for an awesome endeavor.
