### ISSUE TITLE
Hi 

### ISSUE THREAD

**Issue by Rapidwave72** [mdo/feedback#132]
Thank you for taking time to loo at my message. I am new here and the bootstrap on my P.C is loading as notepad. I HAVE A WINDOWS P.C. The issue is I cannot use it as it is just showing the text in Notepad. New so everything is very overwhelming

**Comment by mdo** [comment]
Hey there, you're going to want to give us a bit more details over in an issue on [Bootstrap](https://github.com/twbs/bootstrap/issues/). Bootstrap is responsive, so if your browser is quite narrow, it will appear in "notepad" (tablet) mode.

**Comment by Rapidwave72** [comment]
Hi Mark,

Okay as you can tell, I am a girl with no coding experience, I want to
build an app that lets you smell from your phone. Why, because I love to
smell things and sometimes you go online and you just do not get that level
of responsiveness. I tried opening a repo, cmd, cd desktop, ls,  eeeeeehh.
I ended up with 2 pairs of shoes, due to stress.


Please can you advise on what I should do, whether its even possible. P.S I
know Google did a beta GoogleNose  last April fools.

Thank you
