### ISSUE TITLE
Getbootstrap Expo Jespr.se not mobile responsive

### ISSUE THREAD

**Issue by zrosenbauer** [mdo/feedback#133]
I just wanted you to let them know there site either has a bug or is not set up for mobile (idk how if you're using bootstrap correctly)....it looks great on desktop though

**Comment by mdo** [comment]
Not every site has everything we'd like to showcase, but we still like to share them with folks. Ideally they'd make the site responsive, but there's not much we can do about it. Thanks for reporting though!
