### ISSUE TITLE
Avoid using this branch

### ISSUE THREAD

**Issue by JasonNewton1** [mdo/feedback#134]
Hello Mark,

I am really sorry to bother you. I am forking the Lanyon template to get a site up and running but I am worried about using it. In the usage section, it states: "GitHub Pages for our hosted site, which includes our analytics tracking code. Please avoid using this branch."

I'm not really technically minded. Does this mean I cannot fork the repository, and host my own site on Github Pages?

Please could you let me know. I don't want to cause you any hassle.

Regards

**Comment by cjerrington** [comment]
They just do not want google analytics tracking to come from other sources other than their own. You can always remove the GA code and replace it with your own or remove all together.

**Comment by mdo** [comment]
Yup, that's about it. You can still fork the repo and what not, but I just want folks to avoid submitting PRs or using that branch as it has some extra bits in it just for me.
