### ISSUE TITLE
font size and line height

### ISSUE THREAD

**Issue by iffyuva** [mdo/feedback#135]
is there any relation between font size and line height. i was going through bootstrap docs http://getbootstrap.com/css/#type and found this:

> Bootstrap's global default `font-size` is 14px, with a `line-height` of 1.428

how did you arrive at these defaults?

**Comment by mdo** [comment]
This creates a 20px baseline (the calculated line-height of 14 multiplied by 1.428).

**Comment by iffyuva** [comment]
cool. now i need to explore what these baselines are :)

**Comment by iffyuva** [comment]
thanks for your answer @mdo

**Comment by mdo** [comment]
No problem. Some potential reading material:

- http://www.smashingmagazine.com/2012/12/17/css-baseline-the-good-the-bad-and-the-ugly/
- http://alistapart.com/article/settingtypeontheweb
- http://www.stuffandnonsense.co.uk/blog/about/improve_your_web_typography_with_baseline_shift

**Comment by iffyuva** [comment]
thanks for the links. going to look into them now.
