### ISSUE TITLE
Blog Feedback!

### ISSUE THREAD

**Issue by parkr** [mdo/feedback#136]
Hey @mdo!

I would have submitted a PR, but couldn't find the source for your site. Was just checking out your blog post on Primer and my eye was drawn to [a link about Jekyll & Sass](http://markdotto.com/2014/09/25/sass-and-jekyll/), so I clicked. Always interesting to read people's advice on Jekyll!

I just wanted to drop you a line and let you know that you don't need the `sass` gem explicitly installed as your guide details, it comes [bundled with jekyll-sass-converter!](https://github.com/jekyll/jekyll-sass-converter/blob/master/jekyll-sass-converter.gemspec#L18)

The rest of the guide is, of course, spot on. There are [further configuration options allowed on GitHub Pages](https://github.com/jekyll/jekyll-sass-converter/blob/master/lib/jekyll/converters/scss.rb#L36-L41) but not sure if they're worth mentioning.

Also _also_ found out the other day that you're old buds with Rob Sayre, who now sits next to me at work. So that's cool! Small world. :smiley: 

Thanks man! Hope you have a dope Monday.

**Comment by mdo** [comment]
Snap, thanks dude! Just fixed that up and added a note about the edit. And yeah, Rob and I worked on a few things together at Twitter—love that guy :).

**Comment by parkr** [comment]
Thanks for the speedy response! Thanks for being such an awesome proponent of Jekyll! :metal: :tada:
