### ISSUE TITLE
wtfhtmlcss.com: Position and width

### ISSUE THREAD

**Issue by geoffyuen** [mdo/feedback#137]
You mention that you should "not set a width on an element that has position: [absolute|fixed];, left, and right." Just curious as why you shouldn't do this. Is it because you don't need to? or are there ill effects?

**Comment by mdo** [comment]
Just that you don't need to. Either set the `width` or specify the `left` and `right`.

**Comment by bradwestfall** [comment]
Also you can have some box model issues by setting width (namely that width applies itself to the content layer by default) so width 100% could give you more than you wanted if you have padding and borders involved. Of course this can be solved by applying `box-sizing` to things but in general having `left: 0` and `right: 0` is less problematic. Not to mention, you actually can't have `width` applied with `left` and `right` - one of those concepts will cancel out the other one. I forget which one wins
