### ISSUE TITLE
Bootstrap 4 Release Guesstimate

### ISSUE THREAD

**Issue by mwsasser** [mdo/feedback#138]
Do you have a month in mind or time frame for the release of Bootstrap 4?  Some of the new features mentioned here are tantalizing.  http://iamkevinrhodes.com/top-5-bootstrap-4-features-coming-2015/

**Comment by mdo** [comment]
I suppose that guy has just been following along with the blog posts and other comments we're making here, but don't get attached to anything he's specifically mentioned :).

I've no time frame to give you. I'm swamped with work at GitHub and don't want to release something half assed, even if it's an alpha. Apologies for all the delays <3.
