### ISSUE TITLE
CamelCase or snake_case for jQuery?

### ISSUE THREAD

**Issue by richgcook** [mdo/feedback#139]
CamelCase or snake_case for jQuery? I remember reading your CSS best practice a while back and 100% agreed so curious now for JS.

**Comment by mdo** [comment]
I don't have a JS preference unfortunately, so I'd defer to almost anyone else on the matter :). That said, I feel like camelCase is the more popular within repos I've worked on.

**Comment by richgcook** [comment]
@mdo Thanks bud!
