### ISSUE TITLE
Front end dev

### ISSUE THREAD

**Issue by jamez14** [mdo/feedback#142]
I'm a developer and specialize in front end development. I'm also really knowledgeable about a couple of server side languages (C# & a little PHP). I eventually want to move out to the west coast to work at a company who's doing great things or is on their way to doing so.

My question is this: I know C#/.Net is not hugely popular out there. As a front end developer, is it nearly mandatory for me to learn another server side language such as Ruby or Java or something else? I don't want to pigeonhole myself into front end only, as I want to be as diverse as possible.

Thanks for all the great work you've done!

**Comment by zacharysohovich** [comment]
I wouldn't say it's mandatory, especially for a front-end. But I'd definitely recommend learning JavaScript, brush up on your PHP, start your portfolio, and maybe add Ruby later.

**Comment by mdo** [comment]
JavaScript is all the rage, yeah. I know lots of companies are leaning more into Java and Scala for things, too. Ruby's still highly relevant. Nothing wrong with having breadth of skills in this field though. I know none of these myself and stick to design and HTML/CSS and I'm doing okay :D.

**Comment by jamez14** [comment]
Cool, thanks for the info & response!
