### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by gradykelly** [mdo/feedback#143]
Hey Mark,

My name is Grady. I am a UX designer. I have been using Bootstrap for some time. I have also made toolkits in the past for Bootstrap for Adobe Fireworks. (fireworkstoolkits.com)

I have been recently switching from Fireworks to Sketch and would love to get the jump on getting a toolkit made for Bootstrap 4. I am guessing that it is in a private repo? I know it is probably asking a lot, but I would like to get access to it. I wouldn't release anything until you release v4.

I could even do a version to include in github repo for designers to use.

Let me know what you think!

Grady Kelly
grady@gradykelly.com
@gradykelly.com
http://ux.gradykelly.com

**Comment by mdo** [comment]
Nothing to share yet, and too soon to start making assets like that :).
