### ISSUE TITLE
primer style guide

### ISSUE THREAD

**Issue by danielone** [mdo/feedback#144]
hi mark, for the primer style guide, do you guys auto generate the style guide or is it custom done? I am looking to make a style guide for our CSS/SCSS and like to have as automated as possible & best practice tips in general for creating such a style guide but so it easy to maintain

best
daniel

**Comment by mdo** [comment]
Totally custom, built on Jekyll. The focus is more on the content and so I decided to write all that custom in a couple days. We used to automate our stuff with KSS, but actually found it more difficult to maintain and convey more meaningful information. For example, most of the automated docs just reiterated what you could glean from reading the source code. Our Primer docs now tell a bit more about how and why, as well as some other helpful context for things.

With Jekyll, it's all Markdown, hosted on GitHub, and uses the built-in Sass compiler. Pretty easy honestly, though not fully automated.

**Comment by danielone** [comment]
Thank you @mdo !!

**Comment by tanem** [comment]
Hey Mark,

We're in the process of setting up a UI styleguide at my day job. We started with KSS but pretty much ran into this as well:

> We used to automate our stuff with KSS, but actually found it more difficult to maintain and convey more meaningful information.

For that reason we’re thinking of switching to a custom/in-house built thing that’s a lot like Primer.

I’m curious though, were there any other pros and cons of a static styleguide like Primer that you haven’t mentioned, especially when compared with the old KSS solution?

My gut feel is that a lot of the potential downsides of a static styleguide can be mitigated via things like making it as easy as possible to update (e.g. using markdown for docs), and having a decent dev workflow (e.g. styleguide in separate repo, code-reviewed PRs to update). Would love to hear your thoughts though.

Thanks :)

**Comment by mdo** [comment]
Markdown is huge—writing just text helps out a lot, especially when you don't have to escape HTML and what not. Separate repo is debatable—we got along great with our earlier styleguide in the `github/github` repo. The only problem was a lack of that meaningful information that KSS didn't really encourage in our docs. I'm sure other tools address that more.

Primer is all in one—the docs are side by side with the source code. Divorcing docs from source is painful though as you really need to be updating both at the same time.

**Comment by tanem** [comment]
Cool, cheers @mdo! :+1:
