### ISSUE TITLE
Theme used in markdotto.com

### ISSUE THREAD

**Issue by hTrap** [mdo/feedback#145]
Hello,
I really like the theme you used on your website, however i could not find it anywhere, the closest i came to it was http://pixyll.com/ which still has a lot of difference. Is your theme forkable? If it is please let me know where i can find it and If it is not ,what is the closest clone you might suggest?

**Comment by mdo** [comment]
It's not available for public usage, sorry. There are similar-ish themes I've made for Jekyll that are open sourced at http://getpoole.com though.
