### ISSUE TITLE
Bootstrap 4 release date update ?

### ISSUE THREAD

**Issue by TomVanWauwe** [mdo/feedback#146]
Hi,
because we are planning to include Bootstrap in our projects, I was wondering if it still would make sense to go with v3.3.4 or wait for v4 as I don't know if there will be future versions 3.x ?

PS: I've read somewhere that v4 will be made in SCSS. Does this mean that there will be no LESS-version anymore ?

**Comment by mdo** [comment]
The official release date is :soon:.

Yes, it'll be Sass-based (`.scss`). I personally have no plans to do a Less version.

**Comment by TomVanWauwe** [comment]
Can you explain what soon is ? Probably already in a few weeks ? Or a few months ? I understand it's practically impossible to be 100 % sure over the exact release date, but as we want to start converting to BS as soon as possible and for now that is v3.3.4 and I hear rumours about v4 being radically different then v3.3.4 (including the need to rewrite parts of your html ), we would like to have as much info as possible before taking a clear decision.

**Comment by mdo** [comment]
I can't give you a date honestly. The alpha is getting closer and closer, but the amount of time we can put into it is variable every week. I'd keep going with v3 for now honestly.

**Comment by koistya** [comment]
@mdo the alpha version is being developed in a private repo for now? It seems like it's not in the original [bootstrap repo](https://github.com/twbs/bootstrap).

**Comment by mdo** [comment]
Yes, it's in a private repo.

**Comment by beingsagir** [comment]
Hi @mdo,
Any news on release date of bs4? We are planning to deploy a project in 3months and continue the long term development process. So we want our stack with most updated tech. What do you suggest? Should we go for bs4?

**Comment by mensfeld** [comment]
@mdo I have the same question - is there any time schedule for b4?

**Comment by mkarlsson** [comment]
@mdo Thanks for all your hard work on this, really appreciate it! How much more work do you think it will take to release candidate? Are you planning on releasing RC's or directly to "RTM"? Would be super awesome to read a blog post or semothing about the state of Bootstrap 4!

**Comment by maroonedsia** [comment]
Hello @mdo,

It is July 2016, and the latest update on Bootstrap 4 is published on Bootstrap's blog on Dec 2015.
Could you please update us on this? Many people like me have the same question. I am, personally, interested in start learning Bootstrap 4, as soon as it reaches a feature freeze.

Thanks for not leaving us in shadows. 
Sia

**Comment by ahmad2smile** [comment]
come on!! Its been ages since last update on your blog about bs4.. Just release it already.

**Comment by ispulkit** [comment]
Lol guys. Thanks for Bootstrap3 and everything. But now it looks like the production in this project is dead. I'm switching to other frameworks like Materialize and foundation. Btw thanks again for Boostrap but it has been ages for v4 to be in alpha. No offence to anyone.

**Comment by ahmad2smile** [comment]
True !! @ispulkit  already switched to Materialize !! its beautiful and hell of a lot easy to use

**Comment by stefaneidelloth** [comment]
A life sign!  
Bootstrap 4 beta just released: 
http://blog.getbootstrap.com/

**Comment by ahmad2smile** [comment]
alot more good options are here now... no one should use bootstrap anymore... It was a great product but it's too generic now...

**Comment by mdo** [comment]
@ahmad2smile Yes, there are tons of options out there—take your pick!

**Comment by mdo** [comment]
Locking this since it's a two year old thread and the OP's issue has been resolved.
