### ISSUE TITLE
What is the theme used on http://markdotto.com/?

### ISSUE THREAD

**Issue by igrishaev** [mdo/feedback#147]
Hi Mark!
I've just started learning Jekyll. Your site looks great. Could you tell me what theme do you use and are the any sources of your site on the GitHub?

Thanks,
Ivan.

**Comment by matiassingers** [comment]
@mdo has answered similar questions a couple of times previously:

- https://github.com/mdo/feedback/issues/41
- https://github.com/mdo/feedback/issues/97
- https://github.com/mdo/feedback/issues/145

**Comment by mdo** [comment]
Yup, @matiassingers basically covered it :grin:.

**Comment by igrishaev** [comment]
Got it, thanks.
