### ISSUE TITLE
What's a good text color besides rgb(0, 0, 0)?

### ISSUE THREAD

**Issue by Pacerier** [mdo/feedback#149]
I see that you use `rgb(85, 85, 85)` for [your site](https://archive.is/P3m11).

But Github is using `rgb(51, 51, 51);`. (Also, you're a designer on GitHub right?)

**Comment by mdo** [comment]
Not sure it really matters so long as you meet minimum contrast compliance and have legible type styles. I typically use `#333` or something close to it.

**Comment by Pacerier** [comment]
Oh.. had thought more research had been done on this.

Btw, are you a designer on GitHub?

**Comment by mdo** [comment]
> Btw, are you a designer on GitHub?

Yup!

**Comment by Pacerier** [comment]
Are you part of the team deciding the colors on Github's website? 

Because, I see that Github uses many different shades of gray. Are they actually just based on "random feel" or is there some kind of "research" on it?

**Comment by mdo** [comment]
> Are you part of the team deciding the colors on Github's website?

Most folks just use a color that comes to mind, but we're working on simplifying that down a bit. We just did a release that combined all our instances of `#777` and `#999` to be a single color that passes AA contrast requirements.

There's no research here—just experience and preference.

**Comment by Pacerier** [comment]
Thanks for the info =)

Also, by "AA contrast requirements", you're referring to?

**Comment by mdo** [comment]
See tools like http://webaim.org/resources/contrastchecker/ and the spec http://www.w3.org/TR/WCAG20/.
