### ISSUE TITLE
Selector collision in combined single CSS file

### ISSUE THREAD

**Issue by maliayas** [mdo/feedback#150]
Hello,

When you combine all of the GitHub's CSS into one file, how can you make sure that there is no selector collision? It seems you don't use a method like unique container classes per page that acts as a namespace.

**Comment by mdo** [comment]
> When you combine all of the GitHub's CSS into one file, how can you make sure that there is no selector collision?

We compile our source Sass files into two bundles—`github` and `github2`. We avoid collisions in that every component *should* have a unique set of classes for it. We don't automate this at all, but perhaps we could.

> It seems you don't use a method like unique container classes per page that acts as a namespace.

Don't do that—you're just automatically making things more specific. Design and develop around individual components, not full pages.

**Comment by maliayas** [comment]
Thanks very much for the response. I'm a fan of your workflows at GitHub. Cheers.
