### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by ericmartel** [mdo/feedback#151]
Hey Mark,

First, a feedback form through Github is a pretty clever idea!

Tonight you marked as Will Not Fix the two contributions I had made to Bootstrap.  Don't get me wrong, I do this all day on the project I work on at Ubi, I understand the necessity to cut some stuff, especially when a new version is coming up.

I can't hide that I was bummed to see that my contributions went nowhere, so I'm asking you first hand, is there something you know I should work on to help out the project?  I'm a Lead AI Programmer at Ubisoft, I'm not a web developer, but I find web dev exciting and finally pitching in to help out a project like Bootstrap was an interesting experience, so I'd gladly do it again!

Thanks!

Eric

**Comment by mdo** [comment]
Hey there!

Sorry about that. Bootstrap is at a weird place right now with v3 so close to end of life and v4's first public alpha coming soon. We're being stretched really thin right now and have to punt on a lot of stuff so we can focus on bigger chunks of v4 and more.

I'm stoked you're looking to contribute. Right now, v3 is largely frozen except for critical bug fixes, straightforward docs changes, and easy CSS tweaks. No new features, no refactors, etc. That's all that's being worked on there from here out. If you can hold out just a little longer, we'll have plenty of things to do once the alpha lands :D.

If you do see something that'd be pretty easy for you to tackle and you think might fit that criteria, open an issue and we can talk about it :).

<3

**Comment by ericmartel** [comment]
No worries!  Really looking forward to see v4!  Like I commented on a few of my PRs, I was hoping to refactor a good chunk of code having to do with available screen space, so I'll see if those ideas still make sense when v4 is released :)

Also, if you're a fan of Ubi Games, let me know, I can hook you up :)
